//
// Created by olidiaks on 28.04.23.
//

#ifndef PROJEKT_PODBIJANIE_KAMPUSU_MICROSOFTU_GAME_H
#define PROJEKT_PODBIJANIE_KAMPUSU_MICROSOFTU_GAME_H


class Game {

};


#endif //PROJEKT_PODBIJANIE_KAMPUSU_MICROSOFTU_GAME_H
